# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_image',
            field=models.ImageField(upload_to='articales/iii'),
        ),
    ]
