# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20160403_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_id',
            field=models.ForeignKey(default=datetime.datetime(2016, 4, 3, 9, 28, 4, 252202, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='blog.Comments'),
            preserve_default=False,
        ),
    ]
