# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20160403_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Articles'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comments'),
        ),
    ]
