# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-04 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20160403_0931'),
        ('blog', '0009_userprofile_website'),
    ]

    operations = [
    ]
