# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-04 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20160404_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_id',
            field=models.ForeignKey(default=id, on_delete=django.db.models.deletion.CASCADE, to='blog.Comments'),
        ),
    ]
